module.exports = {
  WRONG_USER_OR_PASSWORD: 1,
  WRONG_TOKEN: 2,
  WRONG_PARAMS: 3,
  SERVER_ERROR: 4,
  NOT_FOUND: 5,
  REQUIRED: 6,
  WRONG_JSON: 7,
  WRONG_FILE_FORMAT: 8,
  TOO_LARGE_FILE: 9,
  TOO_SMALL_SIZE: 10,
  ACCESS_DENIED: 11,
  WRONG_FORMAT: 12,
};
